# Generated by Django 5.2.8 on 2026-09-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_complaintfeedback_wasteclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('overflowing_bin', 'Overflowing Bin'), ('garbage_on_road', 'Garbage on Road'), ('missed_collection', 'Missed Collection'), ('illegal_dumping', 'Illegal Dumping'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_address', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='user_app.commonincident'),
        ),
    ]
