# Generated by Django 5.2.8 on 2026-09-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_commonincident_complaint_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
